add loadbalancer rake task
pulibrary/oawaiver pull request #219
Opened 2024-11-12 11:26 UTC by kayiwa

add two tasks:
one that allow us to remove an endpoint from serving to the
loadbalancer
another that will put it back on the loadbalancer

closes #218

2024-11-12 13:19 UTC, carolyncole requested changes
Thank you @kayiwa.  I think you will need to do a `bundle update --conservative health-monitor-rails` for this code to work.

2024-11-12 17:40 UTC, maxkadel commented
There's actually a breaking change for Rails 7.2 in the 12.4.1 release, so you have to pin to release 12.4.0. You need to change the line in Gemfile for health-monitor-rails to `gem 'health-monitor-rails', '12.4.0'`

2024-11-13 14:12 UTC, maxkadel requested changes
Thanks Francis! Couple small changes.

2024-11-13 14:12 UTC, maxkadel commented on config/initializers/health_monitor.rb
>        Honeybadger.notify(e)
In the example we don't report to Honeybadger if it's this specific check, so it doesn't get hammered

```suggestion
      Honeybadger.notify(e) unless e.is_a?(HealthMonitor::Providers::FileAbsenceException)
```

2024-11-13 14:12 UTC, maxkadel commented on config/deploy.rb
> +  desc "Marks the server(s) to be removed from the loadbalancer"
```suggestion
  desc "Marks the server(s) to be added back to the loadbalancer"
```

2024-11-13 20:36 UTC, maxkadel commented on config/deploy.rb
> +desc "Marks the server(s) to be removed from the loadbalancer"
Needs the namespace
```suggestion
namespace :application do
  desc "Marks the server(s) to be removed from the loadbalancer"
```

2024-11-15 14:32 UTC, maxkadel approved these changes
Thanks @kayiwa!

2024-11-15 16:30 UTC, tpendragon approved these changes

2024-11-15 16:31 UTC, merged